FROM python:3.10-slim                           
ENV PYTHONUNBUFFERED=1 PYTHONPATH=/app:$PYTHONPATH
WORKDIR /app


ENV PYTHONUNBUFFERED=1  

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && python  -m nltk.downloader -q stopwords  

COPY . .
ENV PORT=8080
CMD ["celery", "-A", "tasks", "worker","-Q", "crawler", "-l", "info", "--concurrency", "4"]
